name: user_location
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  change_app_package_name: ^1.1.0
  google_maps_flutter: ^2.4.0
  location: ^5.0.0
  sqflite: ^2.3.0
  provider: ^6.0.5
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
